### ISSUE TITLE
PA: Authentication, Login/Signup/Demo Login

### ISSUE THREAD

**Issue by kscali** [kscali/pretty-little-things#2]
- [x] Deploy to Heroku.

- [x]  Create backend auth.

- [x] Create frontend auth.

- [x] Create Sign in/ log in form.

**Comment by andywynkoop** [comment]
# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by kscali** [comment]
Hey Andy. I finished the Auth portion. Let me know what you think. I tried to refactor but I'm not sure it's possible with my setup. Let me know what you think. Thanks.

**Comment by andywynkoop** [comment]
Hey! Here are a few suggested changes:
- [ ] From my screen, it looks like some of the text is spilling out of the modal (privacy policy & terms)
- [ ] I should be able to "click out" of the modal by clicking somewhere else on the screen; you could probably do this easily by adding an onClick to the outer modal window (gray part) and closing the modal if the target and currentTarget are the same
- [ ] If you want to use percentages to set things like height/width, make sure the element is inside a container with a fixed width This will help things look consistent across screens and prevent other elements from "clumping" together. For example, I think you should set a fixed height and width for the inner modal content.
You can start with these things for now, I'll give you more feedback once we figure out the 500 error

**Comment by kscali** [comment]
Strange. Where is it spilling out? On my local drive it's fine. But I'll make sure to do the other stuff. For the 500 error. It's saying  Undefined Table: relation "users" does not exist. So does that have to do with migrating my table into heroku's database like you mentioned?

**Comment by andywynkoop** [comment]
I think if you give it a fixed height it will solve the spilling problem

**Comment by andywynkoop** [comment]
And probably width also

**Comment by kscali** [comment]
Ok. Finally! fixed all issues. Cross my fingers. It seems to be workin in heroku.
